taco:
  orders:
    page-size: 10

spring:
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: tacocloud.order.queue
  rabbitmq:
    template:
      exchange: tacocloud.orders
      routing-key: kitchens.central
      receive-timeout: 30000
